-- Tables of the "Hooks Demo" app. The prefix hkd_ keeps them out of the adm_ namespace.
--
-- None of these tables has a foreign key into ADM on purpose: ADM ids are stored as plain
-- numbers (up to 32 digits, so never `integer`). A restricting constraint would make ADM's
-- own delete fail, and a log row is worth keeping after the document it describes is gone.
--
-- Re-runnable: a table that exists is left alone.

declare
  procedure ensure_table (
    p_table_name in varchar2
  , p_ddl        in varchar2
  )
  as
    l_exists number;
  begin
    select count(*)
      into l_exists
      from user_tables
     where table_name = upper(p_table_name);

    if l_exists = 0 then
      execute immediate p_ddl;
    end if;
  end ensure_table;
begin
  -- The registry of the asynchronous workflows. The worker only runs the enabled ones.
  ensure_table('HKD_WORKFLOWS', q'[
    create table hkd_workflows (
      workflow_code varchar2(30 char)   not null
    , hook_key      varchar2(255 char)  not null
    , sort_order    number(3)           not null
    , name          varchar2(100 char)  not null
    , description   varchar2(1000 char) not null
    , enabled_flag  varchar2(1 char)    default on null 'Y' not null
    , constraint hkd_workflows_pk primary key (workflow_code)
    , constraint hkd_workflows_enabled_ck check (enabled_flag in ('Y', 'N'))
    )
  ]');

  -- The synchronous guard: uploads with one of these extensions are refused by the hook.
  ensure_table('HKD_BLOCKED_EXTENSIONS', q'[
    create table hkd_blocked_extensions (
      extension  varchar2(20 char)  not null
    , reason     varchar2(200 char) not null
    , created_at timestamp with local time zone default on null current_timestamp not null
    , constraint hkd_blocked_extensions_pk primary key (extension)
    , constraint hkd_blocked_extensions_ck check (extension = lower(extension) and instr(extension, '.') = 0)
    )
  ]');

  -- Written by the guard in an AUTONOMOUS transaction. The hook aborts the upload by raising,
  -- which rolls the whole transaction back - a plain insert here would vanish with it.
  ensure_table('HKD_REJECTIONS', q'[
    create table hkd_rejections (
      rejection_id number generated by default on null as identity
    , hook_key     varchar2(255 char)  not null
    , subject      varchar2(1000 char) not null
    , reason       varchar2(1000 char) not null
    , rejected_by  varchar2(255 char)
    , rejected_at  timestamp with local time zone default on null current_timestamp not null
    , constraint hkd_rejections_pk primary key (rejection_id)
    )
  ]');

  -- One row per workflow per processed event: the answer to "what happened to my file?".
  ensure_table('HKD_WORKFLOW_RUNS', q'[
    create table hkd_workflow_runs (
      run_id        number generated by default on null as identity
    , msg_id        raw(16)
    , hook_key      varchar2(255 char)  not null
    , workflow_code varchar2(30 char)   not null
    , document_id   number
    , version_id    number
    , folder_id     number
    , subject       varchar2(1000 char)
    , status        varchar2(10 char)   not null
    , summary       varchar2(1000 char)
    , actor         varchar2(255 char)
    , enqueued_at   timestamp with local time zone
    , processed_at  timestamp with local time zone default on null current_timestamp not null
    , attempt       number(3)           default on null 1 not null
    , constraint hkd_workflow_runs_pk primary key (run_id)
    , constraint hkd_workflow_runs_status_ck check (status in ('OK', 'FLAGGED', 'FAILED', 'SKIPPED'))
    )
  ]');

  -- The outbox. A real system would send mail or call a webhook from here; the demo only
  -- records what it would have sent.
  ensure_table('HKD_NOTIFICATIONS', q'[
    create table hkd_notifications (
      notification_id number generated by default on null as identity
    , document_id     number
    , recipient       varchar2(255 char)  not null
    , subject         varchar2(500 char)  not null
    , body            varchar2(4000 char) not null
    , created_at      timestamp with local time zone default on null current_timestamp not null
    , constraint hkd_notifications_pk primary key (notification_id)
    )
  ]');
end;
/

declare
  l_exists number;
begin
  select count(*) into l_exists from user_indexes where index_name = 'HKD_WORKFLOW_RUNS_DOC_IX';
  if l_exists = 0 then
    execute immediate 'create index hkd_workflow_runs_doc_ix on hkd_workflow_runs (document_id)';
  end if;
end;
/

comment on table hkd_workflows is 'Registry of the asynchronous workflows the worker can run for an event. Only enabled ones run.';
comment on column hkd_workflows.hook_key is 'The ADM hook event (adm_hooks_api.c_after_*) the workflow reacts to.';
comment on table hkd_blocked_extensions is 'File extensions the synchronous upload guard refuses. Lowercase, without the dot.';
comment on table hkd_rejections is 'Uploads the guard refused. Written autonomously because the rejection rolls the upload back.';
comment on table hkd_workflow_runs is 'Outcome of each workflow for each processed queue message. status FLAGGED means it ran and found something worth a look, SKIPPED that the event was not one it applies to.';
comment on column hkd_workflow_runs.attempt is 'Which delivery attempt of the queue message this run belongs to.';
comment on table hkd_notifications is 'Simulated outbox: what the demo would have sent by mail or webhook.';

-- Seed data. merge, so a re-run neither duplicates nor resets what someone toggled: the texts
-- are refreshed, enabled_flag is left alone.
merge into hkd_workflows t
using (
  select 'INTAKE_CLASSIFY' as workflow_code
       , 'AFTER_NEW_FILE_UPLOAD' as hook_key
       , 10 as sort_order
       , 'Intake classification' as name
       , 'Classifies a new file as invoice, contract, image, spreadsheet and so on from its name and type, and tags the document in ADM with the category. Contracts and invoices also get a needs-review tag.' as description
    from dual
  union all
  select 'DUPLICATE_SCAN'
       , 'AFTER_NEW_FILE_UPLOAD'
       , 20
       , 'Duplicate and integrity scan'
       , 'Compares the new file''s checksum with every other live document. An exact copy is flagged and tagged duplicate-of; a file over 10 MB is flagged as large.'
    from dual
  union all
  select 'VERSION_DIGEST'
       , 'AFTER_NEW_FILE_VERSION'
       , 30
       , 'Version change digest'
       , 'Compares a new version with the one before it, flags one that shrank by more than half, and writes a notification for the document owner into the outbox.'
    from dual
  union all
  select 'FOLDER_BLUEPRINT'
       , 'AFTER_NEW_FOLDER_CREATION'
       , 40
       , 'Project folder blueprint'
       , 'A folder created directly inside a folder named Projects gets the standard sub folders 01_Contracts, 02_Deliverables and 03_Archive.'
    from dual
) s
on (t.workflow_code = s.workflow_code)
when matched then
  update set t.hook_key    = s.hook_key
           , t.sort_order  = s.sort_order
           , t.name        = s.name
           , t.description = s.description
when not matched then
  insert (workflow_code, hook_key, sort_order, name, description)
  values (s.workflow_code, s.hook_key, s.sort_order, s.name, s.description);

merge into hkd_blocked_extensions t
using (
  select 'exe' as extension, 'Executables are not documents' as reason from dual
  union all select 'bat', 'Batch scripts are not documents' from dual
  union all select 'cmd', 'Command scripts are not documents' from dual
  union all select 'scr', 'Screen savers are executables in disguise' from dual
) s
on (t.extension = s.extension)
when not matched then
  insert (extension, reason)
  values (s.extension, s.reason);
