-- Build workflows on hooks: setup. Run in SQLcl or SQL*Plus, connected as the ADM schema owner.
--
--   @00_setup.sql
--
-- What it does:
--   1. checks the prerequisites and prints one line for each
--   2. creates the two tables lesson 1 needs (hkd_blocked_extensions, hkd_rejections)
--   3. creates the folder hkd_tutorial in the home folder of the ADM user named below
--
-- Re-runnable: a table that exists is left alone, and so are its rows. Every object has the
-- prefix hkd_. 99_teardown.sql removes all of it.
--
-- The tutorial acts as one ADM user. Change the name on the next line if your ADM user is not ADMIN.
-- (Lesson pages and the other scripts name ADMIN too: replace it there as well.)

define hkd_user = ADMIN

set define on
set verify off
set serveroutput on
set feedback off
whenever sqlerror exit failure

prompt
prompt === Prerequisites ===

declare
  l_count number;
  l_taken number;
begin
  select count(*)
    into l_count
    from adm_hooks;
  dbms_output.put_line('1. ADM is installed (' || l_count || ' hook events).');

  -- Lesson 2 needs Advanced Queuing. A grant through a role does not count in a stored package, so look at the
  -- direct grants only. This is a warning, not a stop: lesson 1 needs nothing from it.
  select count(*)
    into l_count
    from user_tab_privs
   where owner      = 'SYS'
     and table_name in ('DBMS_AQ', 'DBMS_AQADM')
     and privilege  = 'EXECUTE'
     and grantee    = user;
  if l_count < 2 then
    dbms_output.put_line('2. NOT YET: the schema cannot use Advanced Queuing. Lesson 2 needs it. Ask a DBA to run:');
    dbms_output.put_line('   grant execute on sys.dbms_aqadm to ' || user || ';');
    dbms_output.put_line('   grant execute on sys.dbms_aq to ' || user || ';');
  else
    dbms_output.put_line('2. The schema can use Advanced Queuing.');
  end if;

  select count(*)
    into l_count
    from session_privs
   where privilege in ('CREATE TYPE', 'CREATE JOB', 'CREATE TABLE', 'CREATE PROCEDURE');
  if l_count < 4 then
    dbms_output.put_line('   Warning: the schema needs the privileges CREATE TABLE, CREATE PROCEDURE, CREATE TYPE and CREATE JOB.');
  end if;

  select count(*)
    into l_taken
    from adm_hooks
   where hook_plsql is not null
     and hook_plsql not like 'hkd_hook_api.%';
  if l_taken > 0 then
    raise_application_error(-20700, 'Another hook is already registered. ADM allows one snippet for each event. '
      || 'Read adm_hooks.hook_plsql. Use a schema without hooks for this course, or call the old code from hkd_hook_api.');
  end if;
  dbms_output.put_line('3. The hook slots are free.');

  select count(*)
    into l_count
    from adm_users
   where username = upper('&hkd_user')
     and is_active = 'Y';
  if l_count = 0 then
    raise_application_error(-20700, 'No active ADM user named &hkd_user.. Edit the define line at the top of this script.');
  end if;
  dbms_output.put_line('4. The ADM user &hkd_user. exists.');
end;
/

prompt
prompt === Tables ===

declare
  procedure ensure_table (
    p_table_name in varchar2
  , p_ddl        in varchar2
  )
  as
    l_exists number;
  begin
    select count(*)
      into l_exists
      from user_tables
     where table_name = upper(p_table_name);

    if l_exists = 0 then
      execute immediate p_ddl;
    end if;
  end ensure_table;
begin
  ensure_table('HKD_BLOCKED_EXTENSIONS', q'[
    create table hkd_blocked_extensions (
      extension  varchar2(20 char)  not null
    , reason     varchar2(200 char) not null
    , created_at timestamp with local time zone default on null current_timestamp not null
    , constraint hkd_blocked_extensions_pk primary key (extension)
    , constraint hkd_blocked_extensions_ck check (extension = lower(extension) and instr(extension, '.') = 0)
    )
  ]');

  ensure_table('HKD_REJECTIONS', q'[
    create table hkd_rejections (
      rejection_id number generated by default on null as identity
    , hook_key     varchar2(255 char)  not null
    , subject      varchar2(1000 char) not null
    , reason       varchar2(1000 char) not null
    , rejected_by  varchar2(255 char)
    , rejected_at  timestamp with local time zone default on null current_timestamp not null
    , constraint hkd_rejections_pk primary key (rejection_id)
    )
  ]');
end;
/

merge into hkd_blocked_extensions t
using (
  select 'exe' as extension, 'Executables are not documents' as reason from dual
  union all select 'bat', 'Batch scripts are not documents' from dual
  union all select 'cmd', 'Command scripts are not documents' from dual
  union all select 'scr', 'Screen savers are executables in disguise' from dual
) s
on (t.extension = s.extension)
when not matched then
  insert (extension, reason)
  values (s.extension, s.reason);

prompt
prompt === Working folder ===

declare
  l_home   adm_folders.folder_id%type;
  l_folder adm_folders.folder_id%type;
begin
  adm_context_api.system_user_login('&hkd_user');

  l_home := adm_folder_api.get_folder_id('/users/' || lower('&hkd_user'));

  begin
    select folder_id
      into l_folder
      from adm_folders
     where parent_folder_id = l_home
       and folder_name      = 'hkd_tutorial'
       and deleted_flag     = 'N';
  exception
    when no_data_found then
      l_folder := adm_folder_api.add_folder('hkd_tutorial', l_home);
  end;

  commit;
end;
/

set feedback on
select 'setup OK: '
       || (select count(*) from hkd_blocked_extensions) || ' blocked extensions, '
       || (select count(*) from hkd_rejections) || ' refusals logged, folder '
       || (select min(folder_path) from adm_folders where folder_name = 'hkd_tutorial' and deleted_flag = 'N') as result
  from dual;

whenever sqlerror continue
